name: Deploy to Azure
on:
  push:
    branches:
      - main    
env: 
  NODE_VERSION: '16.13.0'
  
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install dependencies
      run: yarn
    
    - name: Build
      run: yarn build

   